imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
doctrine:
    dbal:
        connections:
            default:
                driver:   %test_database_driver%
                host:     %test_database_host%
                port:     %test_database_port%
                dbname:   %test_database_name%
                user:     %test_database_user%
                password: %test_database_password%
                path:     %test_database_path%
                charset:   UTF8
                logging:   false
                profiling: false                 

