security:
    
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]            
#
    access_control:
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #AsseticBundle paths used when using the controller for assets
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/change-password$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/profile$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/profile/edit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register/check-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register/confirm/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register/confirmed$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resseting/request$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resseting/send-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resseting/check-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resseting/reset/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> custom access control for the admin area of the URL
        - { path: ^/client/, role: ROLE_CUSTOMER }
        - { path: ^/provider/, role: ROLE_PROVIDER }
        - { path: ^/admin/, role: ROLE_EDITOR }
        - { path: ^/adminsonata/, role: ROLE_SUPER_ADMIN }
        # DESACTIVER LE FRONT ACCES AUX NON LOGGE
        # - { path: ^/, 'role: ROLE_USER }

    access_denied_url: /unauthorized
    
    access_decision_manager:
        # Strategy can be: affirmative, unanimous or consensus
        strategy: unanimous
        
    encoders:
        #Sfynx\AuthBundle\Entity\User: sha512 # sha512 plaintext
        FOS\UserBundle\Model\UserInterface: { id: my_password_encoder }
    
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username          
        
    firewalls:
        #
        # By specifying form_login, you have told the Symfony2 framework that any time  
        # a request is made to this firewall that leads to the user needing to authenticate himself, 
        # the user will be redirected to a form where he will be able to enter his credentials.
        #
        
            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        wsse_secure:
            pattern:   ^/api/wsse/v1/.*
            stateless: true
            wsse:      true
            anonymous : true            
            
        # defaut login area for standard users   
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                use_forward: false
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                failure_path: /login_failure
                success_handler: sfynx.auth.authentication_handler
                remember_me: true
                #default_target_path: /home
                #username_parameter: login[_username]
                #password_parameter: login[_password]
            remember_me:
                key: "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER
                remember_me_parameter: _remember_me
            logout:
                path: /logout
                target: /
                success_handler: sfynx.auth.logout_handler
                invalidate_session: false
                #delete_cookies: [sfynx_auth_user]
            anonymous: true
            
# jms_security_extra Configuration
# http://jmsyst.com/bundles/JMSSecurityExtraBundle/master/configuration
jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false # important for optimal perform
    
    # Enables expression language
    expressions: true
    
    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control: { }
    
# jms_di_extra Configuration
# http://jmsyst.com/bundles/JMSDiExtraBundle/master/configuration
jms_di_extra:
    locations:
        all_bundles: true
        directories: ["%kernel.root_dir%/../src", "%kernel.root_dir%/../vendor/sfynx-project"] # important for optimal perform
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
        method_calls:
            setRouter: ["@router"]    
           